### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by vivigirardin**
As discussed in the last S-ENDA DMH group meeting, we (NIVA) got the task to suggest changes on the template that to make it more suitable for all institutes. We worked mainly on chapter 1.

- **Condensed the introduction.** We believe the template has too much text
- **Moved the [table metadata from chapter 1 to glossary](https://github.com/metno/data-management-handbook/blob/72b4f2e416ac32a15e5edf96af73ce4550a2267f/source/glossary.adoc#metadata).** 
- Reorganized Metadata definitions on the glossary table.  
- Shorten chapter 2's title 

We have not looked into the others chapters yet.

### CODE REVIEW

**Comment by vivigirardin** [comment]
We are missing [bencretois](https://github.com/BenCretois). @mortenwh.

**Comment by TAlonglong** [comment]
bencretois invited @vivigirardin

**Review by BenCretois — APPROVED** [review]

**Comment by mortenwh** [comment]
Hi - this is a bit misunderstood. We cannot merge this into master yet. I wanted us to work on issue branches originating from dev, and merge these into dev when they are done. The master branch is the core of METs official DMH, and cannot be changed yet.
@vivigirardin -  I suggest that you and I have a meeting next week to clarify and agree.

**Review by mortenwh — CHANGES_REQUESTED** [review]
As mentioned in previous comment. Please make a new branch with your changes, and make a PR to merge from that to dev instead. I'll close this now, to avoid merging into master.

**Pull request closed without merging**
